#!/usr/bin/env ruby

$LOAD_PATH.push File.expand_path('lib')
$stdout.sync = true

require 'rubygems'
require 'bundler/setup'
require 'beast_saber_sync'

BeastSaberSync.call(username: ARGV[0], path: ARGV[1])
